### ISSUE TITLE
invalid character 'H' looking for beginning of value

### ISSUE THREAD

**Issue by buliugu** [freedomkk-qfeng/windows-agent#1]
注释掉mssql.go里面的github.com/denisenkom/go-mssqldb后编译成功，但是运行一段时间后log报错call Transfer.Update fail 127.0.0.1:6060 invalid character 'H' looking for beginning of value。

**Comment by freedomkk-qfeng** [comment]
不要注释掉，如果不使用mssql的监控，enbale打成false即可
