### ISSUE TITLE
use panic

### ISSUE THREAD

**Issue by auh201006** [freedomkk-qfeng/windows-agent#6]
D:\Program Files\agent>.\windows-agent.exe
2017/09/27 08:42:43 cfg.go:131: read config file: cfg.json successfully
2017/09/27 08:42:43 var.go:35: logging on windows.log
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x7a784d]

goroutine 10 [running]:
github.com/freedomkk-qfeng/windows-agent/funcs.mssqlMetrics(0x0, 0x0, 0x0)
        E:/gopath/src/github.com/freedomkk-qfeng/windows-agent/funcs/mssql.go:22 +0x8d
github.com/freedomkk-qfeng/windows-agent/cron.collect(0x3c, 0xc042034160, 0x2, 0x2)
        E:/gopath/src/github.com/freedomkk-qfeng/windows-agent/cron/collector.go:47 +0x16b
created by github.com/freedomkk-qfeng/windows-agent/cron.Collect
        E:/gopath/src/github.com/freedomkk-qfeng/windows-agent/cron/collector.go:29 +0xb6

**Comment by freedomkk-qfeng** [comment]
show your cfg.json please

**Comment by auh201006** [comment]
{
    "debug": true,
	"logfile": "windows.log",
    "hostname": "",
    "ip": "",
	"iis":{
		"enabled": false,
		"websites": [
	        "Default Web Site"
	    ]
 	},
    "heartbeat": {
        "enabled": true,
        "addr": "192.168.40.166:6030",
        "interval": 60,
        "timeout": 1000
    },
    "transfer": {
        "enabled": true,
        "addrs": [
            "192.168.40.166:8433"
        ],
        "interval": 60,
        "timeout": 1000
    },
    "http": {
        "enabled": true,
        "listen": ":1988",
        "backdoor": false
    },
    "collector": {
        "ifacePrefix": ["以太网 2"]
    },
    "ignore": {
        "cpu.busy": true
    }
}

**Comment by auh201006** [comment]
the version of open-falcon is v0.2.1

**Comment by freedomkk-qfeng** [comment]
do not remove the mssql config
if you are not using mssql, disable it in the cfg.json, but not remove it
```
	"mssql":{
		"enabled": false,
        ……
```

```
{
    "debug": true,
	"logfile": "windows.log",
    "hostname": "",
    "ip": "",
	"iis":{
		"enabled": false,
		"websites": [
	        "Default Web Site"
	    ]
 	}, 
	"mssql":{
		"enabled": false,
		"addr":"127.0.0.1",
		"port":1433,
		"username":"sa",
		"password":"123456",
		"encrypt":"disable",
		"instance": [
	        "test"
	    ]
 	}, 
    "heartbeat": {
        "enabled": true,
        "addr": "127.0.0.1:6030",
        "interval": 60,
        "timeout": 1000
    },
    "transfer": {
        "enabled": true,
        "addrs": [
            "127.0.0.1:8433"
        ],
        "interval": 60,
        "timeout": 1000
    },
    "http": {
        "enabled": true,
        "listen": ":1988",
        "backdoor": false
    },
    "collector": {
        "ifacePrefix": ["以太网 2"]
    },
    "ignore": {
        "cpu.busy": true
    }
}
```

**Comment by auh201006** [comment]
It worked!
