### ISSUE TITLE
IsTCPPortV4Used   返回错误

### ISSUE THREAD

**Issue by a965331268** [freedomkk-qfeng/windows-agent#8]
windows10 64位， IsTCPPortV4Used 总是返回 false. 
我有一个修正的正确版本：
func IsTCPPortV4Used(port int64) bool {
	if port < minTCPPort || port > maxTCPPort {
		return false
	}
	connString := ":" + strconv.FormatInt(port, 10)
	conn, err := net.Listen("tcp4", connString)
	log.Println(connString, conn, err)
	if err != nil {
		return true
	}
	conn.Close()
	return false
}

func IsTCPPortV6Used(port int64) bool {
	if port < minTCPPort || port > maxTCPPort {
		return false
	}
	connString := "[::]:" + strconv.FormatInt(port, 10)
	conn, err := net.Listen("tcp6", connString)
	log.Println(connString, conn, err)
	if err != nil {
		return true
	}
	conn.Close()
	return false
}

**Comment by freedomkk-qfeng** [comment]
win 这个问题很讨厌。如果采用监听 ":" 的方法来测试，这也会导致 127.0.0.1 上监听的端口检测不到。
目前 1.0.3 上采用同时检测 0.0.0.0 和 127.0.0.1 进行监听测试。
